import { describe, it, expect } from "vitest";
import { parseSpec } from "../../src/codegen/parser.js";
import { generateClient } from "../../src/codegen/generator.js";

const SWAGGER_2_SPEC = {
  swagger: "2.0",
  info: { title: "StudentApi", version: "1.0" },
  basePath: "/StudentApi/api",
  definitions: {
    Student: {
      type: "object",
      required: ["id"],
      properties: {
        id: { type: "string", description: "Student identifier" },
        name: { type: "string" },
        gpa: { type: "number" },
      },
    },
  },
  paths: {
    "/students": {
      get: {
        operationId: "listStudents",
        summary: "List all students",
        tags: ["students"],
        parameters: [
          { name: "limit", in: "query", type: "integer", required: false },
        ],
        responses: {
          "200": {
            schema: { type: "array", items: { $ref: "#/definitions/Student" } },
          },
        },
      },
      post: {
        operationId: "createStudent",
        summary: "Create a student",
        tags: ["students"],
        parameters: [
          {
            name: "body",
            in: "body",
            required: true,
            schema: { $ref: "#/definitions/Student" },
          },
        ],
        responses: {
          "201": { schema: { $ref: "#/definitions/Student" } },
        },
      },
    },
    "/students/{id}": {
      get: {
        operationId: "getStudent",
        summary: "Get a student by ID",
        tags: ["students"],
        parameters: [
          { name: "id", in: "path", type: "string", required: true },
        ],
        responses: {
          "200": { schema: { $ref: "#/definitions/Student" } },
        },
      },
      delete: {
        operationId: "deleteStudent",
        tags: ["students"],
        parameters: [
          { name: "id", in: "path", type: "string", required: true },
        ],
        responses: { "204": {} },
      },
    },
  },
};

describe("generateClient", () => {
  const parsed = parseSpec(SWAGGER_2_SPEC);
  const result = generateClient(parsed, "StudentApi");

  describe("types.ts", () => {
    it("contains auto-generated header", () => {
      expect(result.types).toContain("Auto-generated by ellucian-banner-codegen");
    });

    it("generates Student interface", () => {
      expect(result.types).toContain("export interface Student {");
      expect(result.types).toContain("id: string;");
      expect(result.types).toContain("name?: string;");
      expect(result.types).toContain("gpa?: number;");
    });

    it("includes JSDoc from descriptions", () => {
      expect(result.types).toContain("/** Student identifier */");
    });
  });

  describe("client.ts", () => {
    it("contains auto-generated header", () => {
      expect(result.client).toContain("Auto-generated by ellucian-banner-codegen");
    });

    it("imports BannerApiClient from ellucian-banner", () => {
      expect(result.client).toContain('import { BannerApiClient } from "ellucian-banner"');
    });

    it("imports RequestOptions from ellucian-banner", () => {
      expect(result.client).toContain('import type { RequestOptions } from "ellucian-banner"');
    });

    it("imports types from types.ts", () => {
      expect(result.client).toContain('from "./types.js"');
      expect(result.client).toContain("Student");
    });

    it("generates class extending BannerApiClient", () => {
      expect(result.client).toContain(
        "export class StudentApiClient extends BannerApiClient {",
      );
    });

    it("generates listStudents method", () => {
      expect(result.client).toContain("async listStudents(");
      expect(result.client).toContain("Promise<Student[]>");
      expect(result.client).toContain('this.get<Student[]>("/students"');
    });

    it("generates createStudent method with body", () => {
      expect(result.client).toContain("async createStudent(");
      expect(result.client).toContain("body: Student");
      expect(result.client).toContain("this.post<Student>");
    });

    it("generates getStudent method with path param", () => {
      expect(result.client).toContain("async getStudent(id: string");
      expect(result.client).toContain("this.get<Student>(`/students/${id}`");
    });

    it("generates deleteStudent method returning void", () => {
      expect(result.client).toContain("async deleteStudent(");
      expect(result.client).toContain("Promise<void>");
    });

    it("includes JSDoc for methods with summaries", () => {
      expect(result.client).toContain("/** List all students */");
      expect(result.client).toContain("/** Get a student by ID */");
    });
  });

  it("appends Client suffix if not present", () => {
    const result2 = generateClient(parsed, "MyApi");
    expect(result2.client).toContain("class MyApiClient extends");
  });

  it("does not double the Client suffix", () => {
    const result3 = generateClient(parsed, "MyApiClient");
    expect(result3.client).toContain("class MyApiClient extends");
    expect(result3.client).not.toContain("MyApiClientClient");
  });

  it("generates method name from path when operationId is missing", () => {
    const spec = {
      swagger: "2.0",
      info: { title: "Test", version: "1.0" },
      basePath: "/",
      definitions: {},
      paths: {
        "/things/{id}": {
          get: {
            tags: [],
            parameters: [{ name: "id", in: "path", type: "string", required: true }],
            responses: { "200": { schema: { type: "object" } } },
          },
        },
      },
    };
    const p = parseSpec(spec);
    const r = generateClient(p, "Test");
    expect(r.client).toContain("async getThingsById(");
  });
});
