/**
 * TypeScript code generator.
 *
 * Transforms a {@link ParsedSpec} into ready-to-write TypeScript source files:
 * - `types.ts`  — interfaces from schema definitions
 * - `client.ts` — typed client class extending BannerApiClient
 */

import type { ParsedEndpoint, ParsedSchema, ParsedSchemaProperty, ParsedSpec } from "./parser.js";

// ── Public types ──

export interface GeneratedFiles {
  /** TypeScript source for schema interfaces. */
  types: string;
  /** TypeScript source for the API client class. */
  client: string;
}

// ── Public API ──

/**
 * Generate TypeScript source files from a parsed OpenAPI spec.
 *
 * @param spec   — the parsed intermediate representation
 * @param apiName — class name prefix (e.g. "StudentApi" → StudentApiClient).
 *                  Defaults to the spec title.
 */
export function generateClient(spec: ParsedSpec, apiName?: string): GeneratedFiles {
  const name = sanitizeClassName(apiName ?? spec.title);
  const className = name.endsWith("Client") ? name : `${name}Client`;

  const types = generateTypes(spec.schemas);
  const client = generateClientClass(spec, className);

  return { types, client };
}

// ── Types generation ──

function generateTypes(schemas: Map<string, ParsedSchema>): string {
  const lines: string[] = [
    "// Auto-generated by ellucian-banner-codegen — do not edit",
    "",
  ];

  for (const [name, schema] of schemas) {
    lines.push(...generateInterface(name, schema));
    lines.push("");
  }

  return lines.join("\n");
}

function generateInterface(name: string, schema: ParsedSchema): string[] {
  const interfaceName = toPascalCase(name);
  const lines: string[] = [];

  lines.push(`export interface ${interfaceName} {`);

  if (schema.properties) {
    for (const [propName, prop] of schema.properties) {
      if (prop.description) {
        lines.push(`  /** ${prop.description} */`);
      }
      const optional = prop.required ? "" : "?";
      const tsType = propToTsType(prop);
      lines.push(`  ${propName}${optional}: ${tsType};`);
    }
  }

  lines.push("}");
  return lines;
}

function propToTsType(prop: ParsedSchemaProperty): string {
  if (prop.ref) {
    return toPascalCase(prop.ref);
  }
  if (prop.type === "array") {
    if (prop.items?.ref) {
      return `${toPascalCase(prop.items.ref)}[]`;
    }
    const itemType = prop.items ? schemaToTsType(prop.items) : "unknown";
    return `${itemType}[]`;
  }
  return mapPrimitiveType(prop.type);
}

function schemaToTsType(schema: ParsedSchema): string {
  if (schema.ref) return toPascalCase(schema.ref);
  if (schema.type === "array") {
    const itemType = schema.items ? schemaToTsType(schema.items) : "unknown";
    return `${itemType}[]`;
  }
  return mapPrimitiveType(schema.type);
}

function mapPrimitiveType(type: string): string {
  switch (type) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "object":
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

// ── Client generation ──

function generateClientClass(spec: ParsedSpec, className: string): string {
  const schemaNames = new Set<string>();
  collectUsedSchemaNames(spec, schemaNames);

  const typeImports = [...schemaNames].sort().map((n) => toPascalCase(n));

  const lines: string[] = [
    "// Auto-generated by ellucian-banner-codegen — do not edit",
    "",
    'import { BannerApiClient } from "ellucian-banner";',
    'import type { RequestOptions } from "ellucian-banner";',
  ];

  if (typeImports.length > 0) {
    lines.push(`import type { ${typeImports.join(", ")} } from "./types.js";`);
  }

  lines.push("");
  lines.push(`export class ${className} extends BannerApiClient {`);

  for (const endpoint of spec.endpoints) {
    lines.push(...generateMethod(endpoint, spec.basePath));
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function generateMethod(endpoint: ParsedEndpoint, _basePath: string): string[] {
  const methodName = deriveMethodName(endpoint);
  const pathParams = endpoint.parameters.filter((p) => p.in === "path");
  const queryParams = endpoint.parameters.filter((p) => p.in === "query");
  const hasBody = !!endpoint.requestBody && ["post", "put", "patch"].includes(endpoint.method);
  const returnType = deriveReturnType(endpoint);

  // Build parameter list
  const params: string[] = [];
  for (const p of pathParams) {
    params.push(`${p.name}: ${mapPrimitiveType(p.type)}`);
  }
  if (hasBody) {
    const bodyType = endpoint.requestBody?.ref
      ? toPascalCase(endpoint.requestBody.ref)
      : "unknown";
    params.push(`body: ${bodyType}`);
  }
  if (queryParams.length > 0) {
    const queryType = buildQueryParamsType(queryParams);
    params.push(`query?: ${queryType}`);
  }
  params.push("options?: RequestOptions");

  // Build path expression
  const pathExpr = buildPathExpression(endpoint.path, pathParams);

  const lines: string[] = [];

  // JSDoc
  if (endpoint.summary) {
    lines.push("");
    lines.push(`  /** ${endpoint.summary} */`);
  }

  lines.push(
    `  async ${methodName}(${params.join(", ")}): Promise<${returnType}> {`,
  );

  // Method body
  const httpMethod = endpoint.method;
  if (hasBody) {
    lines.push(
      `    return this.${httpMethod}<${returnType}>(${pathExpr}, body, options);`,
    );
  } else if (httpMethod === "delete") {
    lines.push(`    return this.delete(${pathExpr}, options);`);
  } else {
    lines.push(
      `    return this.${httpMethod}<${returnType}>(${pathExpr}, options);`,
    );
  }

  lines.push("  }");

  return lines;
}

function deriveMethodName(endpoint: ParsedEndpoint): string {
  if (endpoint.operationId) {
    return toCamelCase(endpoint.operationId);
  }
  // Generate from method + path: GET /students/{id} → getStudentsById
  const segments = endpoint.path
    .split("/")
    .filter(Boolean)
    .map((s) => {
      if (s.startsWith("{") && s.endsWith("}")) {
        return "By" + toPascalCase(s.slice(1, -1));
      }
      return toPascalCase(s);
    });
  return toCamelCase(endpoint.method + segments.join(""));
}

function deriveReturnType(endpoint: ParsedEndpoint): string {
  if (endpoint.method === "delete") return "void";
  if (!endpoint.responseSchema) return "unknown";

  const schema = endpoint.responseSchema;
  if (schema.ref) return toPascalCase(schema.ref);
  if (schema.type === "array") {
    const itemType = schema.items?.ref
      ? toPascalCase(schema.items.ref)
      : schema.items
        ? schemaToTsType(schema.items)
        : "unknown";
    return `${itemType}[]`;
  }
  return schemaToTsType(schema);
}

function buildPathExpression(path: string, pathParams: { name: string }[]): string {
  if (pathParams.length === 0) {
    return `"${path}"`;
  }
  // Convert /students/{id} to `/students/${id}`
  let template = path;
  for (const p of pathParams) {
    template = template.replace(`{${p.name}}`, `\${${p.name}}`);
  }
  return `\`${template}\``;
}

function buildQueryParamsType(params: { name: string; type: string; required: boolean }[]): string {
  const props = params.map((p) => {
    const opt = p.required ? "" : "?";
    return `${p.name}${opt}: ${mapPrimitiveType(p.type)}`;
  });
  return `{ ${props.join("; ")} }`;
}

function collectUsedSchemaNames(spec: ParsedSpec, names: Set<string>): void {
  for (const ep of spec.endpoints) {
    if (ep.requestBody?.ref) names.add(ep.requestBody.ref);
    if (ep.responseSchema?.ref) names.add(ep.responseSchema.ref);
    if (ep.responseSchema?.items?.ref) names.add(ep.responseSchema.items.ref);
  }
}

// ── String utilities ──

function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

function toCamelCase(str: string): string {
  const pascal = toPascalCase(str);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function sanitizeClassName(name: string): string {
  return toPascalCase(name.replace(/[^a-zA-Z0-9\s]/g, " "));
}
